stages:
  - build
  - deploy

variables: 
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA

build_job:
  stage: build
  only: ["dev"]
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  tags:
    - ajstag

  before_script:
    - docker info
    - echo 'building job is running'

  script: 
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - cp -f $ENV_FILE .env
    - docker build -t $TAG_COMMIT -t $TAG_LATEST .
    - docker push $TAG_COMMIT
    - docker push $TAG_LATEST
    - docker rmi $TAG_COMMIT
    - docker rmi $TAG_LATEST
