version: "2.4"

services:
  node-backend:
    restart: always
    build:
      context: .
    image: nodebackend
    ports:
      -  "8000:8000"
    volumes:
      - ./public/uploads:/public/uploads
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:12-alpine
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3